import  com.springhow.examples.drools.domain.OrderRequest;

rule "Discount for CARD payment above 10000"
    when
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice > 10000 );
    then
        orderObject.setDiscount(1500);
end;

rule "Discount for CARD payment below 10000"
    when
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice > 5000 && totalPrice < 10000 );
    then
        orderObject.setDiscount(500);
end;
